"""added number plate

Revision ID: ac1752530813
Revises: 5994dcd21488
Create Date: 2024-05-28 20:40:06.881500

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ac1752530813'
down_revision: Union[str, None] = '5994dcd21488'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ownscar', sa.Column('plate_number', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ownscar', 'plate_number')
    # ### end Alembic commands ###
